# Notes:
#   - Minimal appveyor.yml file is an empty file. All sections are optional.
#   - Indent each level of configuration with 2 spaces. Do not use tabs!
#   - All section names are case-sensitive.
#   - Section names should be unique on each level.

#---------------------------------#
#      general configuration      #
#---------------------------------#
version: 0.1.0.{build}
image: Visual Studio 2017
clone_depth: 2
skip_commits:
  files:
   - '**/*.md'
   - .github/*
   - .vscode/*
   - '*.gitignore'

#---------------------------------#
#      environment configuration  #
#---------------------------------#
environment:
  CODECOV_TOKEN:
    secure: O6YZH9O8+5UPwS4c7sX4Bw23erwCjx9iZWrhAHqq6uW7PwFFwuIEtzNg8mcD8RbZ
  default_tests: y

install:
# - ps: .\appveyor\build\VSTSBuildTests.ps1
- ps: .\appveyor\build\build.env.install.ps1

#---------------------------------#
#      build configuration        #
#---------------------------------#

build: false

#---------------------------------#
#      test configuration         #
#---------------------------------#
before_test:
# Display .NET Core version
- cmd: dotnet --version

test_script:
- ps: .\appveyor\build\appveyor.psake.ps1

after_test:
- ps: $testResultsPath = Join-Path $pwd -ChildPath "\appveyor\release\PesterReport"
- ps: $codeCoverageReport = Resolve-Path $testResultsPath\CodeCoverage.xml
- ps: echo "$testResultsPath"
- ps: (New-Object 'System.Net.WebClient').UploadFile("https://ci.appveyor.com/api/testresults/nunit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path $testResultsPath\Unit.TEST.xml))
- ps: |
      $env:PATH = 'C:\msys64\usr\bin;' + $env:PATH
      Invoke-WebRequest -Uri 'https://codecov.io/bash' -OutFile codecov.sh
      bash codecov.sh -f "$testResultsPath\*.xml" -t $env:CODECOV_TOKEN -n SilverLamp -F unittests
branches:
  only:
  - master
  - dev
skip_tags: true


#---------------------------------#
#      deployment configuration   #
#---------------------------------#

# scripts to run before deployment
# before_deploy:
#   - ps: hostname

# for:
# -
#   branches:
#     only:
#       - master

#   deploy:
#     - provider: Environment
#       name: Test PS Gallery
#       on:
#         appveyor_repo_tag: true
